# Generated by Django 4.1.4 on 2022-12-13 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_welcomemessage_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welcomemessage',
            name='slug',
        ),
    ]
