# Generated by Django 4.1.4 on 2022-12-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_welcomemessage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomemessage',
            name='welcomeImage',
            field=models.ImageField(null=True, upload_to='media/%Y/%m/%d'),
        ),
    ]
