# Generated by Django 4.1.4 on 2022-12-16 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Titre')),
                ('description', models.CharField(max_length=500, unique=True, verbose_name='Description')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('postPics', models.ImageField(null=True, upload_to='posts')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'ordering': ['-created_on'],
            },
        ),
    ]
