# Generated by Django 4.1.4 on 2022-12-18 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_category_subcategory_post_category_post_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='post.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcategory',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='post.subcategory'),
        ),
    ]
